<?php

namespace Database;

define('DBHOST', 'localhost');
define('DBNAME', 'studb');
define('DBUSER', 'root');
define('DBPW', 'mYSql@server.25');
define('TBLSTUDENT', 'tblstudents');
define('TBLFACULTY', 'tblfaculties');
define('TBLYEAR', 'tblyears');
define('TBLGENERATION', 'tblgenerations');
define('TBLGROUP', 'tblstudygroups');
define('TBLSUBJECT', 'tblsubjects');
define('TBLREGISTRATION', 'tblregistrations');
define('TBLATTENDACE', 'tblattendance');
define('TBLSEMESTER', 'tblsemesters');
define('TBLSCORE', 'tblScores');
define('BASE_URL', "/student-management-system/");

?>